Switch to src/
Azordev/did-app pull request #80
Opened 2022-09-12 20:12 UTC by AdrianFagilde

Change the " ../.../" by "src/"

2022-09-13 02:06 UTC, Israel-Laguan approved these changes

2022-09-13 13:14 UTC, Eghinner approved these changes

2022-09-13 16:10 UTC, victor-heliomar approved these changes
Good work!

2022-09-13 16:13 UTC, victor-heliomar requested changes
Good work man! I just have some doubts

2022-09-13 16:13 UTC, victor-heliomar commented on src/actions/EventsActions.ts
> +import { EventByPKReturnTypes } from './../utils/apollo.types';
Why not use src here?

2022-09-13 16:13 UTC, victor-heliomar commented on src/actions/EventsActions.ts
>  import { EVENTS, EVENT_BY_ID_QUERY } from '../services';
Why not use src here?

2022-09-13 16:13 UTC, victor-heliomar commented on src/actions/EventsActions.ts
>  import { useQuery, getListOfEventsReturnTypes, Event } from '../utils';
Why not use src here?

2022-09-14 15:25 UTC, heliomar-pena commented on src/pages/Event/Event.layout.vue
>  import DIDLogo from '../../assets/logos/didperu-dark.svg';
```suggestion
import DIDLogo from 'src/assets/logos/didperu-dark.svg';
```

2022-09-14 15:26 UTC, victor-heliomar commented on src/pages/Home/Home.layout.vue
>  import DIDLogoDark from '../../assets/logos/didperu-dark.svg';
```suggestion
import DIDLogoDark from 'src/assets/logos/didperu-dark.svg';
```

2022-09-14 15:26 UTC, victor-heliomar approved these changes
Good work!

2022-09-14 15:30 UTC, victor-heliomar approved these changes
last changes

2022-09-14 15:30 UTC, victor-heliomar commented on src/pages/Product/Product.layout.vue
> +import DetailLayout from '../../components/DetailLayout';
```suggestion
import DetailLayout from 'src/components/DetailLayout';
```

2022-09-14 15:30 UTC, victor-heliomar commented on src/pages/Home/index.vue
> +import { Event, getUser, Provider, User } from '../../utils';
```suggestion
import { getListOfEventsForHome, getListOfProviders } from 'src/actions';
import { Event, getUser, Provider, User } from 'src/utils';
```

2022-09-14 15:30 UTC, victor-heliomar commented on src/pages/Home/Home.layout.vue
> +import DIDLogoDark from '../../assets/logos/didperu-dark.svg';
```suggestion
import { ProviderCard, EventCard } from 'src/components';
import { Event, EventType, Provider, User } from 'src/utils';
import { handleUserData } from 'src/utils';
import DIDLogoDark from 'src/assets/logos/didperu-dark.svg';
```

2022-09-14 15:35 UTC, merged